window.onload = function() {
    var names = ['Corie Hillard','Max Smith','Aidan Wiltrout','Jaime Brant','Lily Beitzel','Alex Fish','Caleb Pickrel','Joe Emerick-Housel','Wyett Brown','Colton Short','Jaime Brant','Taylor Wright','Ally Walls','Jordan French','Jacob Bell','Bethany Woolley','Emily Li','Maddox Fickes','Zack Snyder','Matt Csencsics','Ethan Platt','Caleb Platt','Carson Hochard','Aiden DiFebo','Alex Nair','Brett Custer','Austin Augustine','Ayden Smorto','Olivia Burk','Josh McCool','Naveen Sirsikar','Blaise Maizey','Mackenzie Rezk','Tommy Urbain','Tommy Bernard','Alex Tebbs','Aydin Swander','Max Oravec','Christian Swander','Mitch Dumm','Zack Novak','Seth Aspey','Cory Franceschini','Donnavan Sanchez','James McKendree','Deven Young','Chris Ramirez','Jon Eggie','Ian Dobbins','Justin Barkley','Austin Valko','Celena 2','Austin Valko','Jason Hale','Joey Hale','Jacob Miller','Mikel Gray','Addison Cann','Aaron Martin','Benjamin Layton','Jadon Stains','Ian Smith','Chris Ramirez','Jon Eggie','Ian Dobbins','Austin Valko','Issac Valko','Jacob Miller','Mikel Gray','James McKendree','Ryan La','Dominick Toribio','Austin Spotts','Jeremiah Beuca','Kash Bridgment','Jordan Kohl','Noah Knoll','Brennen Himes','Shawn Barkley','Arek Donitzen','Rodney Thomas','Bryce Fisher','Kooper Bauldoff','Tanner Hardison','Tyler Hrivnak','Chris McKendrick','Wayne Manna','Devin Barrett','Sedtavious Crochron','Chole Phillips','Kooper Baldauf','Ezekiel Whitmore','Vincent Patalski','AJ Visco','Evan Payne','Kirk Jeffries','Dylan Holmes','Rye McWilliams','Nick Sandrock','Jacob Scharritter','Jason Pernick','Ryan Litzinger','Jacob K','Jake Pleins','AJ Visco','AJ Slack','Emily Truong','Brayden Seech','Skyler Hado','Connor Ad','Dylan Holmes','Rye McWilliams','Ryan Litzinger','Vincent Patalski','Evan Payne','Kaden Cramer','Zhen Miller','Josiah Miller','Noah Gilmore','Brody Shaffer','Caden Montgomery','Tyler Miller','Jorden Melton','Aaron Makay','Brock Jensen','Cole Hyatt','Noah Finzel'];

    var users = ['Lazerbeamfan634#4222','stinkispageti#4947','Saint#0430','Jaime05#1305','Sylvie#8359','Kibby#3927','Winter is aw','Joe2227','1T Echo','TTVDinnger','Destroy926','Marshmallowjoe','SinisterPig','TSAVOPROWLER','Scrubudubdub777','Ghastlygirl2476','Dauntless#7828','BeesFav','KITTENSPY','ArsynUwU','ETHAN','Chipotle207','Joe.','Asuperbro','xAlexNair','FaZeNiGhTmArE29','Augustines25','Twitch.savayka#5307','captin_egg#8307','Jamy#3671','[BCCHS]BubmasterNavoon1s777#1449','duckman#6373','Kenzie#4395','itsmeurbs#5403','yisters#8662','Mouse#5510','PIECE CTRL ToT','m a x.','Kentori77','BC E-Sports 1','EliTTenova','boyracing','ItalianSkimo','StrawberryNova','JabyBamal','Deevo16','Kaede','JegWord','FlipStingray','Persist55','Vako','ccTB12','Vako_','givingyouhale','TheMegaBlaziken','Jak1ep00','Mgray206','Cbg_Hotshot32','Stainedllama64','StrikeForce435','pigbeast','WillyWonka6706','Fantasy','JegWord','FlipStingray99','Vako','SKIP','Jakiep00','mgray206','JabyBamal','GaFungus #9403','Booshi #0727','!Austin #6790','Spoooder #8431','Agar #7215','Obamatone #6998','Noah. #9585','Trojans# 1','Trojans# 2','Trojans# 3','Trojans# 4','Trojans# 5','Trojans# 6','the6evoken#0502','Trojans# 1','Trojans# 2','Trojans# 3','Trojans# 4','Trojans# 5','Trojans# 6','Seried#0649','Blank#3141','Birb','RL: AhhhJayyy','RoyalPayne 126','Ic3y Peeks','pkdyl','Rye_Joe','TizzyWizzy1065','pinto -.-','jasonp03','Ryaguya','Jacob K','DOZY#1117','AJ#6037','Gunzer#9407','Em#9702','QrTr #2570','SpooderDooder#8522','connor#9185','pkdyl','turkey','Ryaguya #7574','Birb','Royal Payne','Iconic_kaden88','Death Storm','SpectralFlash5','Axeplosion','Obsidianfang459','cuboidBison3397','XxTillMillxX','Jordy_is_qt','Aaromi','FancyBJzz','MoistyButtCheeks','JuiceWrd2707'];

    var t = document.getElementsByClassName('sp-data-table');
    for (var j = 0; j < t.length; j++) {
        t[j].id = `table${j}`
        var td = jQuery(`#table${j}`).children('tbody').children('tr').children('td')
        for (var i = 0;i< td.length;i++) {
            if (td[i].innerHTML.includes('<')===false) {
                console.log(td[i].innerHTML.trim());
                if (names.indexOf(td[i].innerHTML.trim()) != -1) {
                    var n = td[i].innerHTML.trim();
                    td[i].innerHTML = users[names.indexOf(n)];
                }
            }
        }
    }
}